### ISSUE TITLE
The current code doesn't accept the previous version of the conversion.json file since the Chatpt began until 20/12/2022  

### ISSUE THREAD

**Issue by ab-almahfadi** [mirableio/chat-history#22]
I have noticed an issue on your project the current code hasn't accepted the previous version of the conversion.json file since the Chatpt began until 20/12/2022 there is an explanation:

### Differences between my modification and your current code In history.py:

1. **Pydantic Usage**:
   - **Difference**: my modification uses Pydantic's `BaseModel` and `Field` for defining the `Part` class, whereas your current code doesn't.
   - **Reason**: Pydantic is a data validation and serialization library. The usage of `BaseModel` suggests that my modification is likely aiming for better data validation and easier serialization/deserialization.

2. **Typing Imports**:
   - **Difference**: my modification has a separate import statement for `typing` functionalities compared to your current code.
   - **Reason**: Different import statements can change how types are referred to in the code. The one in my modification might be more standard or clearer.

3. **Attributes in Part Class**:
   - **Difference**: my modification defines several attributes (like `asset_pointer`, `size_bytes`, etc.) that are not present in your current code.
   - **Reason**: These attributes likely represent important data fields for the `Part` class. Their absence in your current code suggests it might be an incomplete or older version.

4. **Parts Attribute**:
   - **Difference**: Both files have a `parts` attribute, but they are defined differently. your current code has a more complex type hint involving `OrderedDict`.
   - **Reason**: This suggests that the structure of the `parts` attribute was changed or is being considered for a change. The usage of `OrderedDict` might indicate an attempt to maintain the order of elements.

5. **Commented `parent_id`**:
   - **Difference**: your current code has the `parent_id` attribute commented out.
   - **Reason**: It's possible that there was uncertainty about whether this attribute should be included or not. Commenting it out might have been a temporary measure.

### Conclusion:
my modification seems to be a more refined and updated version with better data validation using Pydantic and clearer type hints. It's advisable to consider it as the base and merge any necessary changes from `history.py` if needed.

**Comment by kuchin** [comment]
I don't see any reason to support old export versions. I want to keep the code supporting all the new schema changes, as in my last commits.

**Comment by kuchin** [comment]
I don't see any reason to support old export versions. I want to keep the code supporting all the new schema changes, as in my last commits.

**Comment by ab-almahfadi** [comment]
I think those who have the old versions can't use your last commit. I think that's a logical reason why you should accept modification of old versions.

**Comment by kuchin** [comment]
I don't see a logical reason to open OLD conversation export. You can always download a fresh one. But since it's opensource, feel free to keep the support in your fork.

**Comment by ab-almahfadi** [comment]
oh Sorry, But you don't understand me even if someone exports his conversation today and he had the account before 20/12/2022 he can't show his conversation.
